name: Deploy 11ty Website via SFTP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build 11ty Site
      run: |
        npm install
        npm run build 
        
    - name: Deploy
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        uploads: |
          ./ => ./www/
